### ISSUE TITLE
Remove Tag Hardcoded display names and descriptions

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry.com#887] opened 2018-11-18 16:18 UTC
The presentation of tags for the email settings page should no longer be hard coded. The `/tag/list` api call should contain `display_name` and `description`. The hardcoded area is: 

https://github.com/lbryio/lbry.io/blob/5cb04332c2179209d0ddbee361c576436319871b/controller/action/MailActions.class.php#L79-L121

**Comment by kauffj** [comment] 2019-08-22 17:30
duplicate of #1090

**Closed by kauffj** 2019-08-22 17:30 UTC
